# Workflow for building and deploying both frontend (Node.js/React) and backend (Azure Functions)
name: Build and deploy frontend and backend to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure (Frontend)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5702215CA797484EB4943F6134F4052A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E1DB2BF53D684519A4831758943E592C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_73E802A564FA43499483BBA425037FE3 }}

      - name: 'Deploy to Azure Web App (Frontend)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Campus-Transport' # Name of the Web App hosting the frontend
          slot-name: 'Production'
          package: .
        env:
          REACT_APP_MAPBOX_API_KEY: ${{ secrets.REACT_APP_MAPBOX_PUBLIC_TOKEN }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js (Backend API)
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Build Azure Functions (API)
        run: npm install --prefix api

      - name: Login to Azure (Backend)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5702215CA797484EB4943F6134F4052A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E1DB2BF53D684519A4831758943E592C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_73E802A564FA43499483BBA425037FE3 }}

      - name: Deploy Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'Campus-Transport-API'  # Name of the Azure Function App for APIs
          package: './api'  # Assuming your Azure Functions are located in an 'api' folder
